### ISSUE TITLE
Icon doesn't show up most of the time

### ISSUE THREAD

**Issue by Skellingtor** [Akasiek/spicetify-lucky-lp#2]
Spotify for Windows (32 bits)
1.2.28.581.gd0e8a92c
Spicetify v2.30.0
xpui_2023-12-29_1703813563444_d0e8a92
cef_120.1.9+g3914241+chromium-120.0.6099.109
Runtime: Alloy

I noticed that the extension's icon won't show up most of the time while using Spotify regularly. But it seems that when I open a playlist/album/song from an external source (e.g. clicking a Spotify link in my web browser) the shuffle album option appears again.

See the GIF below for what I mean:

![chrome_sQC1aZicsc](https://github.com/Akasiek/spicetify-lucky-lp/assets/19526287/9717c9f1-43d6-4c54-8702-ee9f99e97a74)

**Comment by Akasiek** [comment]
It should appear on all album pages and on the homepage.

I've encountered this problem when developing the extension. I'll try to fix it. 

If you'd like to help, you can run `spicetify enable-devtools` command in your console - this will open Spicetify in dev mode. You can then access DevTools by pressing the `F12` key. The Console tab may contain some important information about the bug.

**Comment by Skellingtor** [comment]
I noticed the following errors that consistently show up:

> vendor~xpui.js:29 Error: Invalid playlist response!
>     at Go (xpui.js:1:1934789)
>     at Wo.getPlaylist (xpui.js:1:1938439)
>     at async Wo.getMetadata (xpui.js:1:1938665)

> POST https://exp.wg.spotify.com/lfc/lookup net::ERR_FAILED

These two are both related to `vendor~xpui.js:29`.

> Access to fetch at 'https://exp.wg.spotify.com/lfc/lookup' from origin 'https://xpui.app.spotify.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

This one is from `index.html:1`.

**Comment by Akasiek** [comment]
These aren't related to the bug, unfortunately. I have some ideas on how to fix it, but I'm busy with university stuff. I'll try to find some time to fix it.

**Comment by Akasiek** [comment]
Today I opened my Linux workstation and my button was gone too. I uninstalled and reinstalled the extension. Worked like a charm.

This may be a silly question, but have you tried uninstalling and reinstalling the extension?

**Comment by Skellingtor** [comment]
Yes, multiple times and through multiple ways. I can try again since Spotify updated though.

**Comment by Akasiek** [comment]
I made some changes. Small, but it might suddenly work. Try reinstalling the extension from Marketplace.

**Comment by Skellingtor** [comment]
Doesn't seem to have changed anything, unfortunately. The icon disappears when clicking around albums normally and comes up when opening an external link, as I reported above.

**Comment by Akasiek** [comment]
OK. Tried a new approach. Might work.

Try reinstalling the extension, but I don't know how fast the versions are updated on the marketplace. You might want to wait until tomorrow and try again.

**Comment by Skellingtor** [comment]
I'll come back tomorrow to let you know then, I'm not sure how fast the marketplace updates either.

**Comment by Skellingtor** [comment]
Issue seems to have been fixed with the latest Spicetify update (2.31.0).

![Spotify_w2E4CWC0wZ](https://github.com/Akasiek/spicetify-lucky-lp/assets/19526287/4c5de9bb-dcb6-4585-a901-0dc035a0d3c3)

**Comment by Akasiek** [comment]
Glad to hear it!
