### ISSUE TITLE
Extension has stopped working

### ISSUE THREAD

**Issue by Skellingtor** [Akasiek/spicetify-lucky-lp#3]
I hate to be the bringer of bad news again, but the extension has stopped working since the last Spotify update. Not like last time where it worked in specific situations, now it just doesn't work at all. See screenshot below.

Spotify for Windows (32 bit)
1.2.31.1205.g4d59ad7c
Spicetify v2.31.2

![image](https://github.com/Akasiek/spicetify-lucky-lp/assets/19526287/1ae4938e-69a2-4640-af21-710eced9c0d0)

**Comment by Akasiek** [comment]
Well, that's a bummer! Although I think this problem will be easier to solve. At least we're getting an error.

Similar to the last issue, can you post information from the **console tab** in dev mode? To enable dev mode you can run the `spicetify enable-devtools` command in your console. You can then access DevTools by pressing the `F12` key. When you're in the Console tab, try to reproduce the error. Some information should pop up.

**Comment by Skellingtor** [comment]
These are the three errors I got this time:
```
Error: GET request to https://api.spotify.com/v1/tracks/1OqoF7ANdhrrN1gvWI3gN5 request failed with error code -1 (Resolver not found!)
    at l.onFailure (xpui.js:1:2244330)
    at onFailure (xpui.js:1:2243932)
```
```
Uncaught (in promise) Error: GET request to https://api.spotify.com/v1/tracks/1OqoF7ANdhrrN1gvWI3gN5 request failed with error code -1 (Resolver not found!)
    at l.onFailure (xpui.js:1:2244330)
    at onFailure (xpui.js:1:2243932)
```
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getProductState')
    at p.handleProductStateUpdate (xpui.js:1:2412436)
    at p._dispatchFromStore (vendor~xpui.js:1:629844)
    at p.emitSync (vendor~xpui.js:1:631313)
    at s.emitSync (xpui.js:1:2251696)
    at s.emitProductStateUpdate (xpui.js:1:2426382)
    at xpui.js:1:2048879
    at vendor~xpui.js:1:5546410
    at onSuccess (xpui.js:1:2252475)
handleProductStateUpdate @ xpui.js:1
_dispatchFromStore @ vendor~xpui.js:1
emitSync @ vendor~xpui.js:1
emitSync @ xpui.js:1
emitProductStateUpdate @ xpui.js:1
(anonymous) @ xpui.js:1
(anonymous) @ vendor~xpui.js:1
onSuccess @ xpui.js:1
```

**Comment by Akasiek** [comment]
That's weird. Are you using any custom DNS server? Maybe try to run `ping https://api.spotify.com/` in terminal and see if you get any connection to Spotify API server.

**Comment by Skellingtor** [comment]
I hope I did this right, I had to delete the 'https' to get it work. Also, I used ControlD in the past but not anymore so I don't have any DNS servers set up.

```
Pinging edge-web.dual-gslb.spotify.com [2600:1901:1:c36::] with 32 bytes of data:
Reply from 2600:1901:1:c36::: time=8ms
Reply from 2600:1901:1:c36::: time=8ms
Reply from 2600:1901:1:c36::: time=8ms
Reply from 2600:1901:1:c36::: time=8ms

Ping statistics for 2600:1901:1:c36:::
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 8ms, Maximum = 8ms, Average = 8ms
```

**Comment by Akasiek** [comment]
My Spotify just updated and I'm getting the same error. But my dev tools don't show anything. Very weird.

I'll try to fix it later today or sometime this week. It may also be a bug on the Spicetify team side and we'll have to wait.

**Comment by Akasiek** [comment]
![image](https://github.com/Akasiek/spicetify-lucky-lp/assets/37307597/12b0b62c-b857-48bb-a83e-3cd3863849b6)

Official statement from Spicetify team

**Comment by Skellingtor** [comment]
Figures, people were also telling everyone to downgrade on the Discord too. I'll do that as well then, hope they can find a solution soon.

**Comment by Akasiek** [comment]
As of v2.23.0 of Spicetify, the extension works.
